name: Secret Example

on: [push]

jobs:
  RunSomeSecretTask:
    runs-on: ubuntu-latest
    steps:
      - name: Log secret password
        run: echo The secret password is: 
              $SECRET_PASSWORD
         
